name: "Setup Job Environment"
description: "Installs dependencies like dotnet, rust, etc."

inputs:
  update-dotnet:
    description: 'Whether to run the setup-dotnet action'
    required: false
    default: 'false'
  rust-cache:
    description: 'Whether to run the rust-cache action'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Setup dotnet
      if: inputs.update-dotnet == 'true'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          8.0.x
          9.0.x
    - name: Print dotnet version
      shell: pwsh
      run: dotnet --info
    - name: Install NBGV CLI
      shell: pwsh
      run: dotnet tool update -g nbgv
    - uses: dotnet/nbgv@master
      with:
        setAllVars: true
    - name: Update Project Version
      shell: pwsh
      run: ./.github/set-nbgv-version.ps1
    - name: Rust Cache
      if: inputs.rust-cache == 'true'
      uses: Swatinem/rust-cache@v2
      with:
        key: "${{ github.workflow }}"
