[target.x86_64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install -y libssl-dev:$CROSS_DEB_ARCH",
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install -y libssl-dev:$CROSS_DEB_ARCH",
]

[target.aarch64-unknown-linux-gnu.env]
OPENSSL_INCLUDE_DIR = "/usr/include/aarch64-linux-gnu"
OPENSSL_LIB_DIR = "/usr/lib/aarch64-linux-gnu"
OPENSSL_NO_VENDOR = "1"
