using AsmResolver;
using AsmResolver.PE;
using AsmResolver.PE.File;
using AsmResolver.PE.Win32Resources;
using AsmResolver.PE.Win32Resources.Builder;
using AsmResolver.PE.Win32Resources.Icon;
using AsmResolver.PE.Win32Resources.Version;
using Microsoft.Extensions.Logging;
using Velopack.NuGet;
using Velopack.Util;

namespace Velopack.Packaging.Windows;

public class ResourceEdit
{
    const ushort kLangNeutral = 0;
    const ushort kCodePageUtf16 = 1200;

    private readonly string _exePath;
    private readonly ILogger _logger;
    private readonly PEFile _file;
    private readonly ushort _langId = kLangNeutral;

    ResourceDirectory _resources;
    private bool _disposed;

    public ResourceEdit(string exeFile, ILogger logger)
    {
        _exePath = exeFile;
        _logger = logger;
        _file = PEFile.FromBytes(File.ReadAllBytes(exeFile));
        var image = PEImage.FromFile(_file);
        _resources = image.Resources ?? new ResourceDirectory(0u);

        // if there is already a manifest, we want to keep the existing language ID
        try {
            var existingInfo = VersionInfoResource.FromDirectory(_resources);
            if (existingInfo != null) {
                _langId = (ushort) existingInfo.Lcid;
            }
        } catch { }
    }

    public void SetExeIcon(string iconPath)
    {
        ThrowIfDisposed();

        var iconResource = new IconResource(IconType.Icon);

        var group = new IconGroup(1, _langId) {
            Type = IconType.Icon,
        };

        var extractor = new IcoExtract(_logger);
        var frames = extractor.ExtractFrames(new FileInfo(iconPath));

        for (var p = 0; p < frames.Count; p++) {
            var f = frames[p];

            var iconEntry = new IconEntry((ushort) (p + 1), _langId) {
                Width = (byte) f.CookedData.Width,
                Height = (byte) f.CookedData.Height,
                ColorCount = (byte) f.Encoding.PaletteSize,
                Reserved = 0,
                Planes = 1,
                BitsPerPixel = (ushort) f.CookedData.PixelType.BitsPerPixel,
                PixelData = new DataSegment(f.RawData),
            };

            group.Icons.Add(iconEntry);
        }

        iconResource.Groups.Add(group);
        iconResource.InsertIntoDirectory(_resources);
    }

    public void SetVersionInfo(PackageManifest package)
    {
        ThrowIfDisposed();

        // We just replace the entire VersionInfo section, so we know that the
        // VarFileInfo languages will be correct.
        var fileVersion = new Version(package.Version.Major, package.Version.Minor, package.Version.Patch, 0);

        var versionInfo = new VersionInfoResource(_langId);
        versionInfo.FixedVersionInfo.FileOS = FileOS.NT;
        versionInfo.FixedVersionInfo.FileType = FileType.App;
        versionInfo.FixedVersionInfo.FileVersion = fileVersion;
        versionInfo.FixedVersionInfo.ProductVersion = fileVersion;

        StringFileInfo stringInfo = new StringFileInfo();
        versionInfo.AddEntry(stringInfo);

        VarFileInfo varInfo = new VarFileInfo();
        versionInfo.AddEntry(varInfo);

        var stringTable = new StringTable(_langId, kCodePageUtf16);
        stringTable[StringTable.CompanyNameKey] = package.ProductCompany;
        stringTable[StringTable.FileDescriptionKey] = package.ProductDescription;
        stringTable[StringTable.FileVersionKey] = package.Version.ToFullString();
        stringTable[StringTable.LegalCopyrightKey] = package.ProductCopyright;
        stringTable[StringTable.ProductNameKey] = package.ProductName;
        stringTable[StringTable.ProductVersionKey] = package.Version.ToFullString();
        stringTable[StringTable.CommentsKey] = $"Generated by Velopack {VelopackRuntimeInfo.VelopackNugetVersion}";
        stringInfo.Tables.Add(stringTable);

        var varTable = new VarTable();
        varTable.Values.Add(((uint) kCodePageUtf16 << 16) | _langId);
        varInfo.Tables.Add(varTable);

        versionInfo.InsertIntoDirectory(_resources);
    }

    public void CopyResourcesFrom(string otherExeFile)
    {
        ThrowIfDisposed();

        var file = PEFile.FromBytes(File.ReadAllBytes(otherExeFile));
        var image = PEImage.FromFile(file);
        _resources = image.Resources ?? new ResourceDirectory(0u);
    }

    public void Commit()
    {
        ThrowIfDisposed();
        _disposed = true;

        var sortedResources = new ResourceDirectory((uint) 0);
        foreach (var entry in _resources.Entries.OrderBy(e => e.Id).ToArray()) {
            _resources.RemoveEntry(entry.Id);
            sortedResources.Entries.Add(entry);
        }

        var resourceBuffer = new ResourceDirectoryBuffer();
        resourceBuffer.AddDirectory(sortedResources);

        var resourceDirectory = _file.OptionalHeader.GetDataDirectory(DataDirectoryIndex.ResourceDirectory);

        if (resourceDirectory.IsPresentInPE) {
            var section = _file.GetSectionContainingRva(resourceDirectory.VirtualAddress);
            section.Contents = resourceBuffer;
        } else {
            _file.Sections.Add(new PESection(".rsrc", SectionFlags.MemoryRead | SectionFlags.ContentInitializedData, resourceBuffer));
        }

        _file.UpdateHeaders();
        _file.OptionalHeader.SetDataDirectory(DataDirectoryIndex.ResourceDirectory,
            new DataDirectory(resourceBuffer.Rva, resourceBuffer.GetPhysicalSize()));

        IoUtil.Retry(() => {
            using var fs = File.Create(_exePath);
            _file.Write(fs);
        });
    }

    private void ThrowIfDisposed()
    {
        if (_disposed) throw new ObjectDisposedException(nameof(ResourceEdit));
    }
}
