// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * VelopackLocator provides some utility functions for locating the current app important paths (eg. path to packages, update binary, and so forth).
 */
export type VelopackLocatorConfig = { 
/**
 * The root directory of the current app.
 */
RootAppDir: string, 
/**
 * The path to the Update.exe binary.
 */
UpdateExePath: string, 
/**
 * The path to the packages' directory.
 */
PackagesDir: string, 
/**
 * The current app manifest.
 */
ManifestPath: string, 
/**
 * The directory containing the application's user binaries.
 */
CurrentBinaryDir: string, 
/**
 * Whether the current application is portable or installed.
 */
IsPortable: boolean, };
