blank_issues_enabled: true
contact_links:
  - name: Discord Community Support
    url: https://github.com/orgs/community/discussions
    about: If you have questions or need help implementing Velopack in your app, please visit our Discord community.