// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An individual Velopack asset, could refer to an asset on-disk or in a remote package feed.
 */
export type VelopackAsset = {
  /**
   * The name or Id of the package containing this release.
   */
  PackageId: string;
  /**
   * The version of this release.
   */
  Version: string;
  /**
   * The type of asset (eg. "Full" or "Delta").
   */
  Type: string;
  /**
   * The filename of the update package containing this release.
   */
  FileName: string;
  /**
   * The SHA1 checksum of the update package containing this release.
   */
  SHA1: string;
  /**
   * The SHA256 checksum of the update package containing this release.
   */
  SHA256: string;
  /**
   * The size in bytes of the update package containing this release.
   */
  Size: bigint;
  /**
   * The release notes in markdown format, as passed to Velopack when packaging the release. This may be an empty string.
   */
  NotesMarkdown: string;
  /**
   * The release notes in HTML format, transformed from Markdown when packaging the release. This may be an empty string.
   */
  NotesHtml: string;
};
