[package]
name = "velopack-python"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "velopack"
crate-type = ["cdylib"]


[dependencies]
velopack = { path = "../lib-rust" }
pyo3 = { version = "0.25.0", features = ["extension-module", "macros"] }
serde = { workspace = true }
serde_json = { workspace = true }
semver = { workspace = true }

