# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import os
import pathlib
import typing
__all__ = [
    "App",
    "GiteaSource",
    "GithubSource",
    "GitlabSource",
    "HttpSource",
    "UpdateInfo",
    "UpdateManager",
    "UpdateOptions",
    "VelopackAsset",
    "VelopackLocatorConfig",
]

@typing.final
class App:
    r"""
    Python wrapper for VelopackApp with builder pattern
    """
    def __new__(cls) -> App:
        r"""
        Create a new VelopackApp builder
        """
    def set_args(self, args: typing.Sequence[builtins.str]) -> App:
        r"""
        Override the command line arguments used by VelopackApp
        """
    def set_auto_apply_on_startup(self, apply: builtins.bool) -> App:
        r"""
        Set whether to automatically apply downloaded updates on startup
        """
    def on_first_run(self, callback: typing.Any) -> App:
        r"""
        This hook is triggered when the application is started for the first time after installation
        """
    def on_restarted(self, callback: typing.Any) -> App:
        r"""
        This hook is triggered when the application is restarted by Velopack after installing updates
        """
    def on_after_install_fast_callback(self, callback: typing.Any) -> App:
        r"""
        Fast callback hook for after installation (Windows only)
        """
    def on_after_update_fast_callback(self, callback: typing.Any) -> App:
        r"""
        Fast callback hook for after update (Windows only)
        """
    def on_before_update_fast_callback(self, callback: typing.Any) -> App:
        r"""
        Fast callback hook for before update (Windows only)
        """
    def on_before_uninstall_fast_callback(self, callback: typing.Any) -> App:
        r"""
        Fast callback hook for before uninstall (Windows only)
        """
    def run(self) -> None:
        r"""
        Runs the Velopack startup logic
        """

@typing.final
class GiteaSource:
    r"""
    Retrieves available releases from a Gitea repository.
    """
    def __new__(cls, repo_url: builtins.str, access_token: typing.Optional[builtins.str] = None, prerelease: builtins.bool = False) -> GiteaSource:
        r"""
        Create a new GiteaSource.
        - `repo_url`: The URL of the Gitea repository (e.g. "https://gitea.com/myuser/myrepo")
        - `access_token`: Optional Gitea access token (sent as `Authorization: token {token}`).
        - `prerelease`: If true, pre-releases will also be searched/downloaded.
        """

@typing.final
class GithubSource:
    r"""
    Retrieves available releases from a GitHub repository. Supports both github.com
    and GitHub Enterprise instances.
    """
    def __new__(cls, repo_url: builtins.str, access_token: typing.Optional[builtins.str] = None, prerelease: builtins.bool = False) -> GithubSource:
        r"""
        Create a new GithubSource.
        - `repo_url`: The URL of the GitHub repository (e.g. "https://github.com/myuser/myrepo")
        - `access_token`: Optional GitHub access token. Without one, requests are rate limited to 60/hr per IP.
        - `prerelease`: If true, pre-releases will also be searched/downloaded.
        """

@typing.final
class GitlabSource:
    r"""
    Retrieves available releases from a GitLab repository.
    """
    def __new__(cls, repo_url: builtins.str, access_token: typing.Optional[builtins.str] = None, prerelease: builtins.bool = False) -> GitlabSource:
        r"""
        Create a new GitlabSource.
        - `repo_url`: The GitLab API URL (e.g. "https://gitlab.com/api/v4/projects/ProjectId")
        - `access_token`: Optional GitLab access token (sent as PRIVATE-TOKEN header).
        - `prerelease`: If true, upcoming/pre-releases will also be searched.
        """

@typing.final
class HttpSource:
    r"""
    Retrieves updates from a static file host or other web server.
    """
    def __new__(cls, url: builtins.str) -> HttpSource:
        r"""
        Create a new HttpSource with the specified base URL.
        """

@typing.final
class UpdateInfo:
    r"""
    Holds information about the current version and pending updates, such as how many there are, and access to release notes.
    """
    @property
    def TargetFullRelease(self) -> VelopackAsset:
        r"""
        The available version that we are updating to.
        """
    @TargetFullRelease.setter
    def TargetFullRelease(self, value: VelopackAsset) -> None:
        r"""
        The available version that we are updating to.
        """
    @property
    def BaseRelease(self) -> typing.Optional[VelopackAsset]:
        r"""
        The base release that this update is based on. This is only available if the update is a delta update.
        """
    @BaseRelease.setter
    def BaseRelease(self, value: typing.Optional[VelopackAsset]) -> None:
        r"""
        The base release that this update is based on. This is only available if the update is a delta update.
        """
    @property
    def DeltasToTarget(self) -> builtins.list[VelopackAsset]:
        r"""
        The list of delta updates that can be applied to the base version to get to the target version.
        """
    @DeltasToTarget.setter
    def DeltasToTarget(self, value: typing.Sequence[VelopackAsset]) -> None:
        r"""
        The list of delta updates that can be applied to the base version to get to the target version.
        """
    @property
    def IsDowngrade(self) -> builtins.bool:
        r"""
        True if the update is a version downgrade or lateral move (such as when switching channels to the same version number).
        In this case, only full updates are allowed, and any local packages on disk newer than the downloaded version will be
        deleted.
        """
    @IsDowngrade.setter
    def IsDowngrade(self, value: builtins.bool) -> None:
        r"""
        True if the update is a version downgrade or lateral move (such as when switching channels to the same version number).
        In this case, only full updates are allowed, and any local packages on disk newer than the downloaded version will be
        deleted.
        """
    def __new__(cls, TargetFullRelease: VelopackAsset, DeltasToTarget: typing.Sequence[VelopackAsset], IsDowngrade: builtins.bool, BaseRelease: typing.Optional[VelopackAsset] = None) -> UpdateInfo: ...

@typing.final
class UpdateManager:
    def __new__(cls, source: GithubSource  |  GitlabSource  |  GiteaSource  |  HttpSource  |  builtins.str, options: typing.Optional[UpdateOptions] = None, locator: typing.Optional[VelopackLocatorConfig] = None) -> UpdateManager: ...
    def get_current_version(self) -> builtins.str: ...
    def get_app_id(self) -> builtins.str: ...
    def get_is_portable(self) -> builtins.bool: ...
    def get_update_pending_restart(self) -> typing.Optional[VelopackAsset]: ...
    def check_for_updates(self) -> typing.Optional[UpdateInfo]: ...
    def download_updates(self, update_info: UpdateInfo, progress_callback: typing.Optional[typing.Any] = None) -> None: ...
    def apply_updates_and_restart(self, update: UpdateInfo  |  VelopackAsset) -> None: ...
    def apply_updates_and_restart_with_args(self, update: UpdateInfo  |  VelopackAsset, restart_args: typing.Sequence[builtins.str]) -> None: ...
    def apply_updates_and_exit(self, update: UpdateInfo  |  VelopackAsset) -> None: ...
    def wait_exit_then_apply_updates(self, update: UpdateInfo  |  VelopackAsset, silent: builtins.bool = False, restart: builtins.bool = True, restart_args: typing.Optional[typing.Sequence[builtins.str]] = None) -> None: ...

@typing.final
class UpdateOptions:
    r"""
    Options to customise the behaviour of UpdateManager.
    """
    @property
    def AllowVersionDowngrade(self) -> builtins.bool:
        r"""
        Allows UpdateManager to update to a version that's lower than the current version (i.e. downgrading).
        This could happen if a release has bugs and was retracted from the release feed, or if you're using
        ExplicitChannel to switch channels to another channel where the latest version on that
        channel is lower than the current version.
        """
    @AllowVersionDowngrade.setter
    def AllowVersionDowngrade(self, value: builtins.bool) -> None:
        r"""
        Allows UpdateManager to update to a version that's lower than the current version (i.e. downgrading).
        This could happen if a release has bugs and was retracted from the release feed, or if you're using
        ExplicitChannel to switch channels to another channel where the latest version on that
        channel is lower than the current version.
        """
    @property
    def ExplicitChannel(self) -> typing.Optional[builtins.str]:
        r"""
        **This option should usually be left None**.
        Overrides the default channel used to fetch updates.
        The default channel will be whatever channel was specified on the command line when building this release.
        For example, if the current release was packaged with '--channel beta', then the default channel will be 'beta'.
        This allows users to automatically receive updates from the same channel they installed from. This options
        allows you to explicitly switch channels, for example if the user wished to switch back to the 'stable' channel
        without having to reinstall the application.
        """
    @ExplicitChannel.setter
    def ExplicitChannel(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        **This option should usually be left None**.
        Overrides the default channel used to fetch updates.
        The default channel will be whatever channel was specified on the command line when building this release.
        For example, if the current release was packaged with '--channel beta', then the default channel will be 'beta'.
        This allows users to automatically receive updates from the same channel they installed from. This options
        allows you to explicitly switch channels, for example if the user wished to switch back to the 'stable' channel
        without having to reinstall the application.
        """
    @property
    def MaximumDeltasBeforeFallback(self) -> builtins.int:
        r"""
        Sets the maximum number of deltas to consider before falling back to a full update.
        The default is 10. Set to a negative number (eg. -1) to disable deltas.
        """
    @MaximumDeltasBeforeFallback.setter
    def MaximumDeltasBeforeFallback(self, value: builtins.int) -> None:
        r"""
        Sets the maximum number of deltas to consider before falling back to a full update.
        The default is 10. Set to a negative number (eg. -1) to disable deltas.
        """
    def __new__(cls, AllowVersionDowngrade: builtins.bool, MaximumDeltasBeforeFallback: builtins.int, ExplicitChannel: typing.Optional[builtins.str] = None) -> UpdateOptions: ...

@typing.final
class VelopackAsset:
    r"""
    An individual Velopack asset, could refer to an asset on-disk or in a remote package feed.
    """
    @property
    def PackageId(self) -> builtins.str:
        r"""
        The name or Id of the package containing this release.
        """
    @PackageId.setter
    def PackageId(self, value: builtins.str) -> None:
        r"""
        The name or Id of the package containing this release.
        """
    @property
    def Version(self) -> builtins.str:
        r"""
        The version of this release.
        """
    @Version.setter
    def Version(self, value: builtins.str) -> None:
        r"""
        The version of this release.
        """
    @property
    def Type(self) -> builtins.str:
        r"""
        The type of asset (eg. "Full" or "Delta").
        """
    @Type.setter
    def Type(self, value: builtins.str) -> None:
        r"""
        The type of asset (eg. "Full" or "Delta").
        """
    @property
    def FileName(self) -> builtins.str:
        r"""
        The filename of the update package containing this release.
        """
    @FileName.setter
    def FileName(self, value: builtins.str) -> None:
        r"""
        The filename of the update package containing this release.
        """
    @property
    def SHA1(self) -> builtins.str:
        r"""
        The SHA1 checksum of the update package containing this release.
        """
    @SHA1.setter
    def SHA1(self, value: builtins.str) -> None:
        r"""
        The SHA1 checksum of the update package containing this release.
        """
    @property
    def SHA256(self) -> builtins.str:
        r"""
        The SHA256 checksum of the update package containing this release.
        """
    @SHA256.setter
    def SHA256(self, value: builtins.str) -> None:
        r"""
        The SHA256 checksum of the update package containing this release.
        """
    @property
    def Size(self) -> builtins.int:
        r"""
        The size in bytes of the update package containing this release.
        """
    @Size.setter
    def Size(self, value: builtins.int) -> None:
        r"""
        The size in bytes of the update package containing this release.
        """
    @property
    def NotesMarkdown(self) -> builtins.str:
        r"""
        The release notes in markdown format, as passed to Velopack when packaging the release. This may be an empty string.
        """
    @NotesMarkdown.setter
    def NotesMarkdown(self, value: builtins.str) -> None:
        r"""
        The release notes in markdown format, as passed to Velopack when packaging the release. This may be an empty string.
        """
    @property
    def NotesHtml(self) -> builtins.str:
        r"""
        The release notes in HTML format, transformed from Markdown when packaging the release. This may be an empty string.
        """
    @NotesHtml.setter
    def NotesHtml(self, value: builtins.str) -> None:
        r"""
        The release notes in HTML format, transformed from Markdown when packaging the release. This may be an empty string.
        """
    def __new__(cls, PackageId: builtins.str, Version: builtins.str, Type: builtins.str, FileName: builtins.str, SHA1: builtins.str, SHA256: builtins.str, Size: builtins.int, NotesMarkdown: builtins.str, NotesHtml: builtins.str) -> VelopackAsset: ...

@typing.final
class VelopackLocatorConfig:
    r"""
    VelopackLocator provides some utility functions for locating the current app important paths (eg. path to packages, update binary, and so forth).
    """
    @property
    def RootAppDir(self) -> pathlib.Path:
        r"""
        The root directory of the current app.
        """
    @RootAppDir.setter
    def RootAppDir(self, value: builtins.str | os.PathLike | pathlib.Path) -> None:
        r"""
        The root directory of the current app.
        """
    @property
    def UpdateExePath(self) -> pathlib.Path:
        r"""
        The path to the Update.exe binary.
        """
    @UpdateExePath.setter
    def UpdateExePath(self, value: builtins.str | os.PathLike | pathlib.Path) -> None:
        r"""
        The path to the Update.exe binary.
        """
    @property
    def PackagesDir(self) -> pathlib.Path:
        r"""
        The path to the packages' directory.
        """
    @PackagesDir.setter
    def PackagesDir(self, value: builtins.str | os.PathLike | pathlib.Path) -> None:
        r"""
        The path to the packages' directory.
        """
    @property
    def ManifestPath(self) -> pathlib.Path:
        r"""
        The current app manifest.
        """
    @ManifestPath.setter
    def ManifestPath(self, value: builtins.str | os.PathLike | pathlib.Path) -> None:
        r"""
        The current app manifest.
        """
    @property
    def CurrentBinaryDir(self) -> pathlib.Path:
        r"""
        The directory containing the application's user binaries.
        """
    @CurrentBinaryDir.setter
    def CurrentBinaryDir(self, value: builtins.str | os.PathLike | pathlib.Path) -> None:
        r"""
        The directory containing the application's user binaries.
        """
    @property
    def IsPortable(self) -> builtins.bool:
        r"""
        Whether the current application is portable or installed.
        """
    @IsPortable.setter
    def IsPortable(self, value: builtins.bool) -> None:
        r"""
        Whether the current application is portable or installed.
        """
    @property
    def AppImagePath(self) -> typing.Optional[pathlib.Path]:
        r"""
        On Linux, this is the path to the AppImage that launched this program.
        """
    @AppImagePath.setter
    def AppImagePath(self, value: typing.Optional[builtins.str | os.PathLike | pathlib.Path]) -> None:
        r"""
        On Linux, this is the path to the AppImage that launched this program.
        """
    def __new__(cls, RootAppDir: builtins.str | os.PathLike | pathlib.Path, UpdateExePath: builtins.str | os.PathLike | pathlib.Path, PackagesDir: builtins.str | os.PathLike | pathlib.Path, ManifestPath: builtins.str | os.PathLike | pathlib.Path, CurrentBinaryDir: builtins.str | os.PathLike | pathlib.Path, IsPortable: builtins.bool, AppImagePath: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None) -> VelopackLocatorConfig: ...

