// Automatically generated by flapigen
#pragma once

namespace velopack_cpp {
template<bool>
class FooWrapper;
using Foo = FooWrapper<true>;
using FooRef = FooWrapper<false>;
} // namespace velopack_cpp
