name: Build Samples
on:
  workflow_call:

permissions:
  contents: read

env:
  UV_FROZEN: "true"

jobs:
  samples:
    strategy:
      fail-fast: false
      matrix:
        sample:
          - CPlusPlusWidgets
          - CPlusPlusWin32
          - CSharpAvalonia
          - CSharpUno
          - CSharpWpf
          - NodeJSElectron
          - PythonWXPython
          - RustIced
        os: [windows, ubuntu] #, macos]
        include:
          - os: windows
            runner: windows-latest
          - os: ubuntu
            runner: ubuntu-latest
          #- os: macos
          #  runner: macos-latest
        exclude:
          - os: ubuntu
            sample: CPlusPlusWin32
          - os: macos
            sample: CPlusPlusWin32
          - os: ubuntu
            sample: CSharpWpf
          - os: macos
            sample: CSharpWpf
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Install wxWidgets (Windows)
        working-directory: samples/${{ matrix.sample }}
        run: |
          curl -L -o wxWidgets-3.2.6-headers.7z https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.6/wxWidgets-3.2.6-headers.7z
          curl -L -o wxMSW-3.2.6_vc14x_x64_Dev.7z https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.6/wxMSW-3.2.6_vc14x_x64_Dev.7z
          curl -L -o wxMSW-3.2.6_vc14x_x64_ReleaseDLL.7z https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.6/wxMSW-3.2.6_vc14x_x64_ReleaseDLL.7z
          7z x wxWidgets-3.2.6-headers.7z -o".\wxWidgets" -y
          7z x wxMSW-3.2.6_vc14x_x64_Dev.7z -o".\wxWidgets" -y
          7z x wxMSW-3.2.6_vc14x_x64_ReleaseDLL.7z -o".\wxWidgets" -y
          dir wxWidgets
        if: ${{ matrix.sample == 'CPlusPlusWidgets' && matrix.os == 'windows' }}
      - name: Install wxWidgets (MacOS)
        run: brew install wxwidgets
        if: ${{ matrix.sample == 'CPlusPlusWidgets' && matrix.os == 'macos' }}
      - name: Install wxWidgets (Linux)
        run: |
          sudo apt update
          sudo apt-cache search libwxgt*
          sudo apt-cache search libgtk*
          sudo apt install -y libwxgtk3.2-dev libgtk-3-dev
        if: ${{ matrix.sample == 'CPlusPlusWidgets' && matrix.os == 'ubuntu' }}
      - name: Install uv
        run: |
          pip install uv
        if: ${{ matrix.sample == 'PythonWXPython' }}
      - name: Install wxPython (macOS)
        working-directory: samples/${{ matrix.sample }}
        run: |
          pip install -U wxPython
        if: ${{ matrix.sample == 'PythonWXPython' && matrix.os == 'macos' }}
      - name: Install wxPython (Linux)
        run: |
          sudo apt update
          sudo apt install -y python3-wxgtk4.0
        if: ${{ matrix.sample == 'PythonWXPython' && matrix.os == 'ubuntu' }}
      - name: Setup uv venv for wxPython (Linux)
        working-directory: samples/${{ matrix.sample }}
        run: |
          uv venv --system-site-packages
        if: ${{ matrix.sample == 'PythonWXPython' && matrix.os == 'ubuntu' }}
      - name: Setup dotnet
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x
      - name: Install VPK
        run: dotnet tool install -g --prerelease vpk
      - name: Pack Sample (Windows)
        working-directory: samples/${{ matrix.sample }}
        run: .\build.bat 1.0.0
        if: ${{ matrix.os == 'windows' }}
      - name: Pack Sample (Unix)
        working-directory: samples/${{ matrix.sample }}
        run: |
          chmod 755 ./build.sh
          ./build.sh 1.0.0
        if: ${{ matrix.os == 'macos' || matrix.os == 'ubuntu' }}
