name: Build

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-rust:
    uses: ./.github/workflows/build-rust.yml

  build-python:
    uses: ./.github/workflows/build-python.yml
    
  build-tests:
    uses: ./.github/workflows/build-tests.yml
    permissions:
      contents: read
      actions: write
      id-token: write
    secrets: inherit # tests need secrets to run

  build-samples:
    uses: ./.github/workflows/build-samples.yml

  build-packages:
    needs: [build-python, build-rust]
    uses: ./.github/workflows/build-packages.yml

  release:
    runs-on: ubuntu-latest
    needs: [build-packages, build-tests, build-samples]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    permissions:
      actions: write
    steps:
      - name: Invoke Release Workflow
        run: gh workflow run release.yml -f workflow_run_id=${{ github.run_id }}
        env:
          GH_TOKEN: ${{ github.token }}