name: Build Python
on:
  workflow_call:

jobs:
  linux:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: ubuntu-22.04
            target: x86_64
          - runner: ubuntu-22.04
            target: x86
          - runner: ubuntu-22.04-arm
            target: aarch64
          - runner: ubuntu-22.04
            target: armv7
          - runner: ubuntu-22.04
            target: s390x
          - runner: ubuntu-22.04
            target: ppc64le
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Job Environment
        uses: ./.github/actions/job-setup
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          working-directory: src/lib-python
          target: ${{ matrix.platform.target }}
          args: --release --out dist
          sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
          manylinux: auto
      # - name: Build free-threaded wheels
      #   uses: PyO3/maturin-action@v1
      #   with:
      #     working-directory: src/lib-python
      #     target: ${{ matrix.platform.target }}
      #     args: --release --out dist -i python3.13t
      #     sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
      #     manylinux: auto
      - name: Upload wheels
        uses: actions/upload-artifact@v7
        with:
          name: wheels-linux-${{ matrix.platform.target }}
          path: src/lib-python/dist
          retention-days: 1

  musllinux:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: ubuntu-22.04
            target: x86_64
          - runner: ubuntu-22.04
            target: x86
          - runner: ubuntu-22.04
            target: aarch64
          - runner: ubuntu-22.04
            target: armv7
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Job Environment
        uses: ./.github/actions/job-setup
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          working-directory: src/lib-python
          target: ${{ matrix.platform.target }}
          args: --release --out dist
          sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
          manylinux: musllinux_1_2
      # - name: Build free-threaded wheels
      #   uses: PyO3/maturin-action@v1
      #   with:
      #     working-directory: src/lib-python
      #     target: ${{ matrix.platform.target }}
      #     args: --release --out dist -i python3.13t
      #     sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
      #     manylinux: musllinux_1_2
      - name: Upload wheels
        uses: actions/upload-artifact@v7
        with:
          name: wheels-musllinux-${{ matrix.platform.target }}
          path: src/lib-python/dist
          retention-days: 1

  windows:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: windows-latest
            target: x64
            rust_target: x86_64-pc-windows-msvc
          - runner: windows-latest
            target: x86
            rust_target: i686-pc-windows-msvc
          - runner: windows-11-arm
            target: arm64
            rust_target: aarch64-pc-windows-msvc
    steps:
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        if: ${{ matrix.platform.runner == 'windows-11-arm' }}
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Job Environment
        uses: ./.github/actions/job-setup
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
          architecture: ${{ matrix.platform.target }}
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          working-directory: src/lib-python
          target: ${{ matrix.platform.rust_target }}
          args: --release --out dist
          sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
      # - name: Build free-threaded wheels
      #   uses: PyO3/maturin-action@v1
      #   with:
      #     working-directory: src/lib-python
      #     target: ${{ matrix.platform.rust_target }}
      #     args: --release --out dist -i python3.13t
      #     sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
      - name: Upload wheels
        uses: actions/upload-artifact@v7
        with:
          name: wheels-windows-${{ matrix.platform.target }}
          path: src/lib-python/dist
          retention-days: 1

  macos:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Job Environment
        uses: ./.github/actions/job-setup
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - name: Build wheels (aarch64)
        uses: PyO3/maturin-action@v1
        with:
          working-directory: src/lib-python
          target: aarch64
          args: --release --out dist-aarch64
          sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
      - name: Build wheels (x86_64)
        uses: PyO3/maturin-action@v1
        with:
          working-directory: src/lib-python
          target: x86_64
          args: --release --out dist-x86_64
          sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
      # - name: Build free-threaded wheels (aarch64)
      #   uses: PyO3/maturin-action@v1
      #   with:
      #     working-directory: src/lib-python
      #     target: aarch64
      #     args: --release --out dist-aarch64 -i python3.13t
      #     sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
      # - name: Build free-threaded wheels (x86_64)
      #   uses: PyO3/maturin-action@v1
      #   with:
      #     working-directory: src/lib-python
      #     target: x86_64
      #     args: --release --out dist-x86_64 -i python3.13t
      #     sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
      - name: Upload wheels (aarch64)
        uses: actions/upload-artifact@v7
        with:
          name: wheels-macos-aarch64
          path: src/lib-python/dist-aarch64
          retention-days: 1
      - name: Upload wheels (x86_64)
        uses: actions/upload-artifact@v7
        with:
          name: wheels-macos-x86_64
          path: src/lib-python/dist-x86_64
          retention-days: 1

  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Job Environment
        uses: ./.github/actions/job-setup
      - name: Build sdist
        uses: PyO3/maturin-action@v1
        with:
          working-directory: src/lib-python
          command: sdist
          args: --out dist
      - name: Upload sdist
        uses: actions/upload-artifact@v7
        with:
          name: wheels-sdist
          path: src/lib-python/dist
          retention-days: 1
