name: Blacksmith Testbox
on:
  workflow_dispatch:
    inputs:
      testbox_id:
        type: string
        description: "Testbox session ID"
        required: true
  pull_request:
    paths:
      - '.github/workflows/**'

permissions:
  id-token: write
  actions: write
  contents: read

jobs:
  rust:
    runs-on: blacksmith-8vcpu-ubuntu-2404
    steps:
      - name: Begin Testbox
        uses: useblacksmith/begin-testbox@v2
        with:
          testbox_id: ${{ inputs.testbox_id }}
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Job Environment
        uses: ./.github/actions/job-setup
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Install cargo-nextest
        uses: taiki-e/install-action@cargo-nextest
      - name: Run Testbox
        uses: useblacksmith/run-testbox@v2
        if: always()